markdown: redcarpet
name: 18F Guides Template
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Add a new page
  url: add-a-new-page/
  internal: true
  children:
  - text: Make a child page
    url: make-a-child-page/
    internal: true
- text: Add images
  url: add-images/
  internal: true
- text: Update the config file
  url: update-the-config-file/
  internal: true
  children:
  - text: Understanding the `baseurl:` property
    url: understanding-baseurl/
    internal: true
- text: GitHub setup
  url: github-setup/
  internal: true
- text: Post your guide
  url: post-your-guide/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/guides-template

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
